language: generic

os: linux
dist: xenial

env:
  jobs:
    - EMACS_VERSION=24.1
    - EMACS_VERSION=25.1
    - EMACS_VERSION=25.2
    - EMACS_VERSION=26.1
    - EMACS_VERSION=master

jobs:
  allow_failures:
    - env: EMACS_VERSION=master
  
install:
  - curl -fsSL --retry 9 --retry-delay 15 -O "https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz"
  - tar -xzf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export PATH=/tmp/emacs/bin:${PATH}
  # If missing, install cl-lib (introduced in Emacs 24.3)
  - if ! emacs -Q --batch --eval "(require 'cl-lib)" ; then
        curl -Lo cl-lib.el "http://elpa.gnu.org/packages/cl-lib-0.6.1.el" ;
    fi
  - emacs --version

script:
  - make test
